### ISSUE TITLE
Add to Maven central?

### ISSUE THREAD

**Issue by shane-axiom** [bedatadriven/jackson-datatype-jts#2]
Have you considered adding this to Maven central? I think it could be useful for a lot of people, and would increase the visibility of the project.

Also, it strikes me that jackson-jts might be a better name for the project (or even jackson-datatype-jts to follow fasterxml's standards). I have seen other Jackson modules that handle GeoJSON, but yours is the only one I found that deals with JTS.

**Comment by aptogo** [comment]
Any idea when the project will be deployed to maven central?

**Comment by akbertram** [comment]
Almost there -- my release build wasn't accepted as it was missing gpg signatures. Once the maven plugin is setup and jenkins configured should be ready for release. Hope to get to it this week.

**Comment by jitpack** [comment]
Btw, you can already download from https://jitpack.io/#bedatadriven/jackson-datatype-jts/jackson-geojson-0.7 : )

**Comment by regisbamba** [comment]
+1 for Maven support please :-)

**Comment by thiagogcm** [comment]
@jitpack I got an error with this build

error: incompatible types: Class<GeometrySerializer> cannot be converted to Class<? extends JsonSerializer<?>>
    @JsonSerialize(using = GeometrySerializer.class)

**Comment by doom777** [comment]
+1 on maven central

**Comment by nikolauskrismer** [comment]
+1

**Comment by shane-axiom** [comment]
Bumping this again. I tried to add this to a project, was confused why the artifact wasn't found, realized that it wasn't on Maven Central, came to add an issue to request that it be added and found that I had already done so last December. Perhaps if getting this submitted isn't a short term reality then a note could be added to the README explaining that the artifact isn't available? Currently that's not clear.

**Comment by akbertram** [comment]
Ok, I think i've jumped through all the neccessary hoops to get this deployed to central. It's passed all checks and the staging repository has been successfully released. You can see it here:
https://oss.sonatype.org/content/groups/public/com/bedatadriven/jackson-datatype-jts/2.2/

But it doesn't yet come up on maven central. Will check back in 24 hours to see if it just requires a bit of time to fully sync.

**Comment by akbertram** [comment]
Finally added and available!
