### ISSUE TITLE
Add support for GeometryFactory parametrization

### ISSUE THREAD

**Issue by vkasala** [bedatadriven/jackson-datatype-jts#3]
Hi,

It would be nice, if GeometryFactory could be parametrized. e.g. if I want to use Factory with own SRID and PrecisionModel, not the default one. This is not hard, just to add Constructor. Thanks.

Viliam K.

**Comment by vkasala** [comment]
Created pull request.

**Comment by akbertram** [comment]
Fixed by PR #6

**Comment by bowenwr** [comment]
Hey guys, I'm probably just being thick but I updated to the latest version from Maven Central (2.2) and don't see a way to do this. Looked through the code and tests as well and I'm not sure what I'm missing. Was expecting something like:

	SimpleModule geometryModule = new JtsModule(new GeometryFactory(PrecisionModel.FLOATING, 4326));

But I can't find anywhere in the code to pass in my factory, I only see new one being declared. What do I need to do? Thanks!

**Comment by purpleP** [comment]
@bowenwr It haven't been fixed by my pull request if I remember correctly. Bu this would be easy to fix. I probably wouldn't have time to do that in the near future, but you can do it youself

**Comment by akbertram** [comment]
I've released this as version 2.3. Should be available on maven central shortly
