### ISSUE TITLE
3D geometries

### ISSUE THREAD

**Issue by wstoppler** [bedatadriven/jackson-datatype-jts#9]
Are there plans to support 3D geometries (altitudes of Coordinates)?  Both the PointParser and the GeometrySerializer's writePoint only support the x and y fields of a Coordinate.  Would it be possible to include the z field (when populated) as well?

**Comment by JWGmeligMeyling** [comment]
Would indeed be a very nice feature. See also the implementation for the [`LngLatAltDeserializer`](https://github.com/opendatalab-de/geojson-jackson/blob/master/src/main/java/org/geojson/jackson/LngLatAltDeserializer.java) from `geojson-jackson`.

**Comment by akbertram** [comment]
@wstoppler I believe this is resolved by https://github.com/bedatadriven/jackson-datatype-jts/commit/97a79d7e49ac478341a23d34e1b727d10bea5d88
